### ISSUE TITLE
Rendere mapGraphics una libreria statica

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/PRAGA#4]
Renderla statica come le altre librerie usate da Praga permetterebbe di rendere l'eseguibile autocontenuto e non ci si dovrebbe preoccupare di mantenere una versione compatibile con altri programmi (e.g. Criteria3D) installati sulla stessa macchina.

Con AppImage è già virtualmente così, in quanto ogni eseguibile usa la sua personale shared library, rendendola statica si potrebbe avere il medesimo comportamento su CentOS.

**Comment by ftomei** [comment]
In realtà inizialmente era statica, ma ricordo che abbiamo avuto problemi con un compilatore per win (mingw).
Provo da casa (dove ho mingw) e ti faccio sapere se si è risolto.

**Comment by edigiacomo** [comment]
Ok, altrimenti si può configurare statica solo per Linux.

**Comment by lauracosta** [comment]
Ho modificato il .pro di mapGraphics in modo che, per Linux, la compilazione avvenga staticamente. Ora il build di centos fallisce, ubuntu ok.

**Comment by edigiacomo** [comment]
Perfetto, ho aggiornato la pacchettizzazione CentOS.

**Comment by edigiacomo** [comment]
Riapro la issue: vi chiedo se è possibile fare una versione 1.0.1 per poter pacchettizzare la versione con mapGraphics statica.

**Comment by ftomei** [comment]
Ho letto ora, abbiamo avuto la stessa idea, ho fatto una v1.1.0

**Comment by ftomei** [comment]
Ora compila come libreria statica anche su win, se tutto ok chiudiamo issue
